/*
 * Kin Ecosystem
 * Apis for client to server interaction
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ConfigBlockchain
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2018-10-25T17:08:07.569+03:00")
public class ConfigBlockchain {
@SerializedName("horizon_url")
  private String horizonUrl = null;
  @SerializedName("network_passphrase")
  private String networkPassphrase = null;
  @SerializedName("asset_issuer")
  private String assetIssuer = null;
  @SerializedName("asset_code")
  private String assetCode = null;
  
  public ConfigBlockchain horizonUrl(String horizonUrl) {
    this.horizonUrl = horizonUrl;
    return this;
  }

  
  /**
  * Get horizonUrl
  * @return horizonUrl
  **/
  @ApiModelProperty(value = "")
  public String getHorizonUrl() {
    return horizonUrl;
  }
  public void setHorizonUrl(String horizonUrl) {
    this.horizonUrl = horizonUrl;
  }
  
  public ConfigBlockchain networkPassphrase(String networkPassphrase) {
    this.networkPassphrase = networkPassphrase;
    return this;
  }

  
  /**
  * Get networkPassphrase
  * @return networkPassphrase
  **/
  @ApiModelProperty(value = "")
  public String getNetworkPassphrase() {
    return networkPassphrase;
  }
  public void setNetworkPassphrase(String networkPassphrase) {
    this.networkPassphrase = networkPassphrase;
  }
  
  public ConfigBlockchain assetIssuer(String assetIssuer) {
    this.assetIssuer = assetIssuer;
    return this;
  }

  
  /**
  * Get assetIssuer
  * @return assetIssuer
  **/
  @ApiModelProperty(value = "")
  public String getAssetIssuer() {
    return assetIssuer;
  }
  public void setAssetIssuer(String assetIssuer) {
    this.assetIssuer = assetIssuer;
  }
  
  public ConfigBlockchain assetCode(String assetCode) {
    this.assetCode = assetCode;
    return this;
  }

  
  /**
  * Get assetCode
  * @return assetCode
  **/
  @ApiModelProperty(example = "KIN", value = "")
  public String getAssetCode() {
    return assetCode;
  }
  public void setAssetCode(String assetCode) {
    this.assetCode = assetCode;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigBlockchain configBlockchain = (ConfigBlockchain) o;
    return Objects.equals(this.horizonUrl, configBlockchain.horizonUrl) &&
        Objects.equals(this.networkPassphrase, configBlockchain.networkPassphrase) &&
        Objects.equals(this.assetIssuer, configBlockchain.assetIssuer) &&
        Objects.equals(this.assetCode, configBlockchain.assetCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(horizonUrl, networkPassphrase, assetIssuer, assetCode);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigBlockchain {\n");
    
    sb.append("    horizonUrl: ").append(toIndentedString(horizonUrl)).append("\n");
    sb.append("    networkPassphrase: ").append(toIndentedString(networkPassphrase)).append("\n");
    sb.append("    assetIssuer: ").append(toIndentedString(assetIssuer)).append("\n");
    sb.append("    assetCode: ").append(toIndentedString(assetCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



