/*
 * Kin Ecosystem
 * Apis for client to server interaction
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ConfigBlockchain
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2018-06-12T15:56:08.924+03:00")
public class ConfigBlockchain {
@SerializedName("horizon_url")
  private String horizonUrl = null;
  @SerializedName("network_passphrase")
  private String networkPassphrase = null;
  @SerializedName("kin_issuer")
  private String kinIssuer = null;
  @SerializedName("kin_token")
  private String kinToken = null;
  
  public ConfigBlockchain horizonUrl(String horizonUrl) {
    this.horizonUrl = horizonUrl;
    return this;
  }

  
  /**
  * Get horizonUrl
  * @return horizonUrl
  **/
  @ApiModelProperty(value = "")
  public String getHorizonUrl() {
    return horizonUrl;
  }
  public void setHorizonUrl(String horizonUrl) {
    this.horizonUrl = horizonUrl;
  }
  
  public ConfigBlockchain networkPassphrase(String networkPassphrase) {
    this.networkPassphrase = networkPassphrase;
    return this;
  }

  
  /**
  * Get networkPassphrase
  * @return networkPassphrase
  **/
  @ApiModelProperty(value = "")
  public String getNetworkPassphrase() {
    return networkPassphrase;
  }
  public void setNetworkPassphrase(String networkPassphrase) {
    this.networkPassphrase = networkPassphrase;
  }
  
  public ConfigBlockchain kinIssuer(String kinIssuer) {
    this.kinIssuer = kinIssuer;
    return this;
  }

  
  /**
  * Get kinIssuer
  * @return kinIssuer
  **/
  @ApiModelProperty(value = "")
  public String getKinIssuer() {
    return kinIssuer;
  }
  public void setKinIssuer(String kinIssuer) {
    this.kinIssuer = kinIssuer;
  }
  
  public ConfigBlockchain kinToken(String kinToken) {
    this.kinToken = kinToken;
    return this;
  }

  
  /**
  * Get kinToken
  * @return kinToken
  **/
  @ApiModelProperty(value = "")
  public String getKinToken() {
    return kinToken;
  }
  public void setKinToken(String kinToken) {
    this.kinToken = kinToken;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigBlockchain configBlockchain = (ConfigBlockchain) o;
    return Objects.equals(this.horizonUrl, configBlockchain.horizonUrl) &&
        Objects.equals(this.networkPassphrase, configBlockchain.networkPassphrase) &&
        Objects.equals(this.kinIssuer, configBlockchain.kinIssuer) &&
        Objects.equals(this.kinToken, configBlockchain.kinToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(horizonUrl, networkPassphrase, kinIssuer, kinToken);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigBlockchain {\n");
    
    sb.append("    horizonUrl: ").append(toIndentedString(horizonUrl)).append("\n");
    sb.append("    networkPassphrase: ").append(toIndentedString(networkPassphrase)).append("\n");
    sb.append("    kinIssuer: ").append(toIndentedString(kinIssuer)).append("\n");
    sb.append("    kinToken: ").append(toIndentedString(kinToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



