/*
 * Kin Ecosystem
 * Apis for client to server interaction
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * JWTBodyConfirmPaymentPayment
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2018-04-16T18:06:48.710+03:00")
public class JWTBodyConfirmPaymentPayment {
@SerializedName("offer_id")
  private String offerId = null;
  @SerializedName("user_id")
  private String userId = null;
  @SerializedName("date")
  private BigDecimal date = null;
  
  public JWTBodyConfirmPaymentPayment offerId(String offerId) {
    this.offerId = offerId;
    return this;
  }

  
  /**
  * offer id - id is decided by digital service
  * @return offerId
  **/
  @ApiModelProperty(value = "offer id - id is decided by digital service")
  public String getOfferId() {
    return offerId;
  }
  public void setOfferId(String offerId) {
    this.offerId = offerId;
  }
  
  public JWTBodyConfirmPaymentPayment userId(String userId) {
    this.userId = userId;
    return this;
  }

  
  /**
  * user identifier - same value as given by register
  * @return userId
  **/
  @ApiModelProperty(value = "user identifier - same value as given by register")
  public String getUserId() {
    return userId;
  }
  public void setUserId(String userId) {
    this.userId = userId;
  }
  
  public JWTBodyConfirmPaymentPayment date(BigDecimal date) {
    this.date = date;
    return this;
  }

  
  /**
  * date of which payment was received in seconds from epoc
  * @return date
  **/
  @ApiModelProperty(value = "date of which payment was received in seconds from epoc")
  public BigDecimal getDate() {
    return date;
  }
  public void setDate(BigDecimal date) {
    this.date = date;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JWTBodyConfirmPaymentPayment jwTBodyConfirmPaymentPayment = (JWTBodyConfirmPaymentPayment) o;
    return Objects.equals(this.offerId, jwTBodyConfirmPaymentPayment.offerId) &&
        Objects.equals(this.userId, jwTBodyConfirmPaymentPayment.userId) &&
        Objects.equals(this.date, jwTBodyConfirmPaymentPayment.date);
  }

  @Override
  public int hashCode() {
    return Objects.hash(offerId, userId, date);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JWTBodyConfirmPaymentPayment {\n");
    
    sb.append("    offerId: ").append(toIndentedString(offerId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



