/*
 * Kin Ecosystem
 * Apis for client to server interaction
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * JWTBodyPartSender
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2018-07-02T14:15:24.728+03:00")
public class JWTBodyPartSender {
@SerializedName("user_id")
  private String userId = null;
  @SerializedName("title")
  private String title = null;
  @SerializedName("description")
  private String description = null;
  
  public JWTBodyPartSender userId(String userId) {
    this.userId = userId;
    return this;
  }

  
  /**
  * same user_id as in register
  * @return userId
  **/
  @ApiModelProperty(value = "same user_id as in register")
  public String getUserId() {
    return userId;
  }
  public void setUserId(String userId) {
    this.userId = userId;
  }
  
  public JWTBodyPartSender title(String title) {
    this.title = title;
    return this;
  }

  
  /**
  * offer title - appears in order history
  * @return title
  **/
  @ApiModelProperty(required = true, value = "offer title - appears in order history")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }
  
  public JWTBodyPartSender description(String description) {
    this.description = description;
    return this;
  }

  
  /**
  * offer description - appears in order history
  * @return description
  **/
  @ApiModelProperty(required = true, value = "offer description - appears in order history")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JWTBodyPartSender jwTBodyPartSender = (JWTBodyPartSender) o;
    return Objects.equals(this.userId, jwTBodyPartSender.userId) &&
        Objects.equals(this.title, jwTBodyPartSender.title) &&
        Objects.equals(this.description, jwTBodyPartSender.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, title, description);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JWTBodyPartSender {\n");
    
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



