/*
 * Kin Ecosystem
 * Apis for client to server interaction
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Limits
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2018-01-29T14:22:38.269+02:00")
public class Limits {
@SerializedName("supply")
  private Integer supply = null;
  @SerializedName("expiration")
  private String expiration = null;
  
  public Limits supply(Integer supply) {
    this.supply = supply;
    return this;
  }

  
  /**
  * Get supply
  * @return supply
  **/
  @ApiModelProperty(value = "")
  public Integer getSupply() {
    return supply;
  }
  public void setSupply(Integer supply) {
    this.supply = supply;
  }
  
  public Limits expiration(String expiration) {
    this.expiration = expiration;
    return this;
  }

  
  /**
  * Get expiration
  * @return expiration
  **/
  @ApiModelProperty(value = "")
  public String getExpiration() {
    return expiration;
  }
  public void setExpiration(String expiration) {
    this.expiration = expiration;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Limits limits = (Limits) o;
    return Objects.equals(this.supply, limits.supply) &&
        Objects.equals(this.expiration, limits.expiration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(supply, expiration);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Limits {\n");
    
    sb.append("    supply: ").append(toIndentedString(supply)).append("\n");
    sb.append("    expiration: ").append(toIndentedString(expiration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



