/*
 * Kin Ecosystem
 * Apis for client to server interaction
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SpendSubmission
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2018-01-29T14:22:38.269+02:00")
public class SpendSubmission {
@SerializedName("transaction_id")
  private String transactionId = null;
  @SerializedName("sender_address")
  private String senderAddress = null;
  
  public SpendSubmission transactionId(String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

  
  /**
  * Get transactionId
  * @return transactionId
  **/
  @ApiModelProperty(required = true, value = "")
  public String getTransactionId() {
    return transactionId;
  }
  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }
  
  public SpendSubmission senderAddress(String senderAddress) {
    this.senderAddress = senderAddress;
    return this;
  }

  
  /**
  * Get senderAddress
  * @return senderAddress
  **/
  @ApiModelProperty(value = "")
  public String getSenderAddress() {
    return senderAddress;
  }
  public void setSenderAddress(String senderAddress) {
    this.senderAddress = senderAddress;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpendSubmission spendSubmission = (SpendSubmission) o;
    return Objects.equals(this.transactionId, spendSubmission.transactionId) &&
        Objects.equals(this.senderAddress, spendSubmission.senderAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionId, senderAddress);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpendSubmission {\n");
    
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    senderAddress: ").append(toIndentedString(senderAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



