/*
 * Kin Ecosystem
 * Apis for client to server interaction
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SubmissionResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2018-01-28T15:32:32.821+02:00")
public class SubmissionResult {
@SerializedName("order_id")
  private String orderId = null;
  @SerializedName("content")
  private Object content = null;
  
  public SubmissionResult orderId(String orderId) {
    this.orderId = orderId;
    return this;
  }

  
  /**
  * Get orderId
  * @return orderId
  **/
  @ApiModelProperty(required = true, value = "")
  public String getOrderId() {
    return orderId;
  }
  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }
  
  public SubmissionResult content(Object content) {
    this.content = content;
    return this;
  }

  
  /**
  * Get content
  * @return content
  **/
  @ApiModelProperty(required = true, value = "")
  public Object getContent() {
    return content;
  }
  public void setContent(Object content) {
    this.content = content;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubmissionResult submissionResult = (SubmissionResult) o;
    return Objects.equals(this.orderId, submissionResult.orderId) &&
        Objects.equals(this.content, submissionResult.content);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderId, content);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubmissionResult {\n");
    
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



