/*
 * Kin Ecosystem
 * Apis for client to server interaction
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Paging;
import io.swagger.client.model.TransactionHistoryItem;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * TransactionHistoryList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2018-02-12T14:35:13.051+02:00")
public class TransactionHistoryList {
@SerializedName("transactions")
  private List<TransactionHistoryItem> transactions = null;
  @SerializedName("paging")
  private Paging paging = null;
  
  public TransactionHistoryList transactions(List<TransactionHistoryItem> transactions) {
    this.transactions = transactions;
    return this;
  }

  public TransactionHistoryList addTransactionsItem(TransactionHistoryItem transactionsItem) {
    
    if (this.transactions == null) {
      this.transactions = new ArrayList<TransactionHistoryItem>();
    }
    
    this.transactions.add(transactionsItem);
    return this;
  }
  
  /**
  * Get transactions
  * @return transactions
  **/
  @ApiModelProperty(value = "")
  public List<TransactionHistoryItem> getTransactions() {
    return transactions;
  }
  public void setTransactions(List<TransactionHistoryItem> transactions) {
    this.transactions = transactions;
  }
  
  public TransactionHistoryList paging(Paging paging) {
    this.paging = paging;
    return this;
  }

  
  /**
  * Get paging
  * @return paging
  **/
  @ApiModelProperty(value = "")
  public Paging getPaging() {
    return paging;
  }
  public void setPaging(Paging paging) {
    this.paging = paging;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionHistoryList transactionHistoryList = (TransactionHistoryList) o;
    return Objects.equals(this.transactions, transactionHistoryList.transactions) &&
        Objects.equals(this.paging, transactionHistoryList.paging);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactions, paging);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionHistoryList {\n");
    
    sb.append("    transactions: ").append(toIndentedString(transactions)).append("\n");
    sb.append("    paging: ").append(toIndentedString(paging)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



