/*
 * Kin Ecosystem
 * Apis for client to server interaction
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * UserStats
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2018-10-25T17:08:07.569+03:00")
public class UserStats {
@SerializedName("earn_count")
  private BigDecimal earnCount = null;
  @SerializedName("spend_count")
  private BigDecimal spendCount = null;
  @SerializedName("last_earn_date")
  private String lastEarnDate = null;
  @SerializedName("last_spend_date")
  private String lastSpendDate = null;
  
  public UserStats earnCount(BigDecimal earnCount) {
    this.earnCount = earnCount;
    return this;
  }

  
  /**
  * Get earnCount
  * @return earnCount
  **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getEarnCount() {
    return earnCount;
  }
  public void setEarnCount(BigDecimal earnCount) {
    this.earnCount = earnCount;
  }
  
  public UserStats spendCount(BigDecimal spendCount) {
    this.spendCount = spendCount;
    return this;
  }

  
  /**
  * Get spendCount
  * @return spendCount
  **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getSpendCount() {
    return spendCount;
  }
  public void setSpendCount(BigDecimal spendCount) {
    this.spendCount = spendCount;
  }
  
  public UserStats lastEarnDate(String lastEarnDate) {
    this.lastEarnDate = lastEarnDate;
    return this;
  }

  
  /**
  * UTC ISO
  * @return lastEarnDate
  **/
  @ApiModelProperty(example = "2018-09-13T14:33:33Z", value = "UTC ISO")
  public String getLastEarnDate() {
    return lastEarnDate;
  }
  public void setLastEarnDate(String lastEarnDate) {
    this.lastEarnDate = lastEarnDate;
  }
  
  public UserStats lastSpendDate(String lastSpendDate) {
    this.lastSpendDate = lastSpendDate;
    return this;
  }

  
  /**
  * UTC ISO
  * @return lastSpendDate
  **/
  @ApiModelProperty(example = "2018-09-13T14:33:33Z", value = "UTC ISO")
  public String getLastSpendDate() {
    return lastSpendDate;
  }
  public void setLastSpendDate(String lastSpendDate) {
    this.lastSpendDate = lastSpendDate;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserStats userStats = (UserStats) o;
    return Objects.equals(this.earnCount, userStats.earnCount) &&
        Objects.equals(this.spendCount, userStats.spendCount) &&
        Objects.equals(this.lastEarnDate, userStats.lastEarnDate) &&
        Objects.equals(this.lastSpendDate, userStats.lastSpendDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(earnCount, spendCount, lastEarnDate, lastSpendDate);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserStats {\n");
    
    sb.append("    earnCount: ").append(toIndentedString(earnCount)).append("\n");
    sb.append("    spendCount: ").append(toIndentedString(spendCount)).append("\n");
    sb.append("    lastEarnDate: ").append(toIndentedString(lastEarnDate)).append("\n");
    sb.append("    lastSpendDate: ").append(toIndentedString(lastSpendDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



