/*
 * Kin Ecosystem
 * Apis for client to server interaction
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiCallback;
import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.Configuration;
import io.swagger.client.Pair;
import io.swagger.client.ProgressRequestBody;
import io.swagger.client.ProgressResponseBody;


import com.google.gson.reflect.TypeToken;

import java.io.IOException;




import io.swagger.client.model.Error;
import io.swagger.client.model.TransactionHistoryList;


import java.lang.reflect.Type;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;



public class TransactionHistoryApi {
    private ApiClient apiClient;

    public TransactionHistoryApi() {
        this(Configuration.getDefaultApiClient());
    }

    public TransactionHistoryApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    
    /**
     * Build call for getHistory
     * @param X_REQUEST_ID A unique id for the request. A retransmitted request will have the same id (required)
     * @param limit maximum number of items in a list (optional)
     * @param since time based pagination (optional)
     * @param until time based pagination (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
        
     */
    public com.squareup.okhttp.Call getHistoryCall(String X_REQUEST_ID, Integer limit, String since, String until, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/transactions";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (limit != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("limit", limit));
        if (since != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("since", since));
        if (until != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("until", until));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        if (X_REQUEST_ID != null)
        localVarHeaderParams.put("X-REQUEST-ID", apiClient.parameterToString(X_REQUEST_ID));

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json""application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "BearerAuth" };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getHistoryValidateBeforeCall(String X_REQUEST_ID, Integer limit, String since, String until, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        
        // verify the required parameter 'X_REQUEST_ID' is set
        if (X_REQUEST_ID == null) {
            throw new ApiException("Missing the required parameter 'X_REQUEST_ID' when calling getHistory(Async)");
        }
        
        
        com.squareup.okhttp.Call call = getHistoryCall(X_REQUEST_ID, limit, since, until, progressListener, progressRequestListener);
        return call;

        
        
        
        
        
        
    }

    /**
     * get user history
     * get user history
     * @param X_REQUEST_ID A unique id for the request. A retransmitted request will have the same id (required)
     * @param limit maximum number of items in a list (optional)
     * @param since time based pagination (optional)
     * @param until time based pagination (optional)
     * @return TransactionHistoryList
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
        
     */
    public TransactionHistoryList getHistory(String X_REQUEST_ID, Integer limit, String since, String until) throws ApiException {
        ApiResponse<TransactionHistoryList> resp = getHistoryWithHttpInfo(X_REQUEST_ID, limit, since, until);
        return resp.getData();
    }

    /**
     * get user history
     * get user history
     * @param X_REQUEST_ID A unique id for the request. A retransmitted request will have the same id (required)
     * @param limit maximum number of items in a list (optional)
     * @param since time based pagination (optional)
     * @param until time based pagination (optional)
     * @return ApiResponse&lt;TransactionHistoryList&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
        
     */
    public ApiResponse<TransactionHistoryList> getHistoryWithHttpInfo(String X_REQUEST_ID, Integer limit, String since, String until) throws ApiException {
        com.squareup.okhttp.Call call = getHistoryValidateBeforeCall(X_REQUEST_ID, limit, since, until, null, null);
        Type localVarReturnType = new TypeToken<TransactionHistoryList>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * get user history (asynchronously)
     * get user history
     * @param X_REQUEST_ID A unique id for the request. A retransmitted request will have the same id (required)
     * @param limit maximum number of items in a list (optional)
     * @param since time based pagination (optional)
     * @param until time based pagination (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
        
     */
    public com.squareup.okhttp.Call getHistoryAsync(String X_REQUEST_ID, Integer limit, String since, String until, final ApiCallback<TransactionHistoryList> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getHistoryValidateBeforeCall(X_REQUEST_ID, limit, since, until, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<TransactionHistoryList>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    
}
