/*
 * Kin Ecosystem
 * Apis for client to server interaction
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AuthToken;
import io.swagger.client.model.Error;
import io.swagger.client.model.SignInData;
import io.swagger.client.model.UserProfile;

import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for AuthApi
 */
@Ignore
public class AuthApiTest {

    private final AuthApi api = new AuthApi();

    
    /**
     * Activate account
     *
     * Activate account by accepting TOS
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void activateAcountTest() throws ApiException {
        
        AuthToken response = api.activateAcount();

        // TODO: test validations
    }
    
    /**
     * Get user profile
     *
     * Get user profile
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserProfileTest() throws ApiException {
        
        String userId = null;
        
        UserProfile response = api.getUserProfile(userId);

        // TODO: test validations
    }
    
    /**
     * Sign in/ Log in
     *
     * Sign a user into kin marketplace
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void signInTest() throws ApiException {
        
        SignInData signindata = null;
        
        AuthToken response = api.signIn(signindata);

        // TODO: test validations
    }
    
}
