/*
 * Kin Ecosystem
 * Apis for client to server interaction
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Error;
import io.swagger.client.model.OfferList;
import io.swagger.client.model.Order;
import io.swagger.client.model.SubmissionResult;
import io.swagger.client.model.TransactionHistoryList;

import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * 
     *
     * cancel an order
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cancelOrderTest() throws ApiException {
        
        api.cancelOrder();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * create an order for an offer
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createOrderTest() throws ApiException {
        
        Order response = api.createOrder();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * get user history
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getHistoryTest() throws ApiException {
        
        TransactionHistoryList response = api.getHistory();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Return a list of offers
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getOffersTest() throws ApiException {
        
        OfferList response = api.getOffers();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * submit an order
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void submitOrderTest() throws ApiException {
        
        Object body = null;
        
        SubmissionResult response = api.submitOrder(body);

        // TODO: test validations
    }
    
}
