/*
 * Kin Ecosystem
 * Apis for client to server interaction
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Error;
import io.swagger.client.model.Order;
import io.swagger.client.model.Submission;
import io.swagger.client.model.SubmissionResult;

import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for OrdersApi
 */
@Ignore
public class OrdersApiTest {

    private final OrdersApi api = new OrdersApi();

    
    /**
     * cancel an order
     *
     * cancel an order
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cancelOrderTest() throws ApiException {
        
        String orderId = null;
        
        String X_REQUEST_ID = null;
        
        api.cancelOrder(orderId, X_REQUEST_ID);

        // TODO: test validations
    }
    
    /**
     * create an order for an offer
     *
     * create an order for an offer
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createOrderTest() throws ApiException {
        
        String offerId = null;
        
        String X_REQUEST_ID = null;
        
        Order response = api.createOrder(offerId, X_REQUEST_ID);

        // TODO: test validations
    }
    
    /**
     * submit an order
     *
     * submit an order
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void submitOrderTest() throws ApiException {
        
        Submission submission = null;
        
        String orderId = null;
        
        String X_REQUEST_ID = null;
        
        SubmissionResult response = api.submitOrder(submission, orderId, X_REQUEST_ID);

        // TODO: test validations
    }
    
}
